[install]
linker = "isolated"
minimumReleaseAge = 259200
minimumReleaseAgeExcludes = []

[test]
root = "."
coverage = true
coverageReporter = ["text", "lcov"]
coverageDir = "./coverage"
coverageThreshold = { line = 0.9, function = 0.9 }
coverageSkipTestFiles = true
